# Generated by Django 4.1 on 2022-08-15 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0007_quesmodel_userid_usermodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quesmodel',
            name='userid',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='userid',
        ),
    ]
